name: Compile LaTeX and deploy to GitHub pages
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  compile-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          args: -file-line-error -halt-on-error -interaction=nonstopmode -bibtex -output-directory=out -jobname="Construction of Mathematics"
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "out/Construction of Mathematics.pdf"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
